// Birds that have a fan-art replacement card and should be pulled from the
// original deck. One name per entry, spelled as printed on the card.
//
// SAMPLE_LIST is true while this is placeholder data; flip it to false once
// the real list is in so the app stops showing the "sample list" notice.
export const SAMPLE_LIST = false

export const BIRDS: string[] = [
  'American Redstart',
  'Ash-Throated Flycatcher',
  'Asian Emerald Dove',
  'Asian Koel',
  'Audouin’s Gull',
  'Australasian Pipit',
  'Australasian Shoveler',
  'Australian Reed Warbler',
  'Baird’s Sparrow',
  'Bell’s Vireo',
  'Bewick’s Wren',
  'Black Drongo',
  'Black Tern',
  'Black Vulture',
  'Black Woodpecker',
  'Black-Headed Gull',
  'Black-Naped Oriole',
  'Black-Shouldered Kite',
  'Black-Tailed Godwit',
  'Black-Throated Diver',
  'Blue Grosbeak',
  'Blue Rock-Thrush',
  'Blue-Winged Warbler',
  'Brambling',
  'Brant',
  'Bronzed Cowbird',
  'Brown Shrike',
  'Brown-Headed Cowbird',
  'California Condor',
  'Canvasback',
  'Carrion Crow',
  'Cassin’s Sparrow',
  'Cetti’s Warbler',
  'Chimney Swift',
  'Clark’s Grebe',
  'Common Buzzard',
  'Common Cuckoo',
  'Common Goldeneye',
  'Common Little Bittern',
  'Common Loon',
  'Common Merganser',
  'Common Moorhen',
  'Common Nighthawk',
  'Common Nightingale',
  'Common Sandpiper',
  'Common Starling',
  'Common Swift',
  'Common Teal',
  'Common Yellowthroat',
  'Cooper’s Hawk',
  'Corsican Nuthatch',
  'Crested Ibis',
  'Crested Lark',
  'Crested Pigeon',
  'Desert Wheatear',
  'Dickcissel',
  'Double-Crested Cormorant',
  'Eastern Kingbird',
  'Eastern Phoebe',
  'Eastern Rosella',
  'Eleonora’s Falcon',
  'Eurasian Collared-Dove',
  'Eurasian Coot',
  'Eurasian Golden Oriole',
  'Eurasian Hobby',
  'Eurasian Jay',
  'Eurasian Magpie',
  'Eurasian Nutcracker',
  'Eurasian Nuthatch',
  'Eurasian Sparrowhawk',
  'Eurasian Treecreeper',
  'European Honey Buzzard',
  'Ferruginous Hawk',
  'Fire-Fronted Serin',
  'Forster’s Tern',
  'Golden Eagle',
  'Golden Pheasant',
  'Golden-Headed Cisticola',
  'Graceful Prinia',
  'Grasshopper Sparrow',
  'Gray Wagtail',
  'Great Egret',
  'Great Indian Bustard',
  'Great Spotted Woodpecker',
  'Greater Adjutant',
  'Greater Flamingo',
  'Greater Prairie-Chicken',
  'Green Pygmy-Goose',
  'Grey Butcherbird',
  'Grey Shrikethrush',
  'Grey Teal',
  'Grey Warbler',
  'Grey-Headed Mannikin',
  'Greylag Goose',
  'Hooded Merganser',
  'Hooded Warbler',
  'Horned Lark',
  'Horsfield’s Bronze-Cuckoo',
  'Horsfield’s Bushlark',
  'House Crow',
  'House Sparrow',
  'Ibisbill',
  'Inca Dove',
  'Indian Vulture',
  'Kelp Gull',
  'Kererū',
  'King Rail',
  'Korimako',
  'Large-Billed Crow',
  'Lesser Frigatebird',
  'Lesser Whitethroat',
  'Lewin’s Honeyeater',
  'Lincoln’s Sparrow',
  'Little Bustard',
  'Little Egret',
  'Little Grebe',
  'Little Pied Cormorant',
  'Little Ringed Plover',
  'Magpie-Lark',
  'Mallard',
  'Malleefowl',
  'Maned Duck',
  'Masked Lapwing',
  'Moltoni’s Warbler',
  'Montagu’s Harrier',
  'Musk Duck',
  'New Holland Honeyeater',
  'Northern Gannet',
  'Northern Goshawk',
  'Northern Harrier',
  'Orange-Footed Scrubfowl',
  'Oriental Bay-Owl',
  'Pacific Black Duck',
  'Parrot Crossbill',
  'Pesquet’s Parrot',
  'Pheasant Coucal',
  'Pied-Billed Grebe',
  'Pine Siskin',
  'Pink-Eared Duck',
  'Plains-Wanderer',
  'Purple Martin',
  'Rainbow Lorikeet',
  'Red Junglefowl',
  'Red Wattlebird',
  'Red-Backed Fairywren',
  'Red-Backed Shrike',
  'Red-Breasted Merganser',
  'Red-Crowned Crane',
  'Red-Eyed Vireo',
  'Red-Necked Avocet',
  'Red-Vented Bulbul',
  'Red-Wattled Lapwing',
  'Rhinoceros Auklet',
  'Rook',
  'Ruddy Shelduck',
  'Rufous Owl',
  'Rufous-Banded Honeyeater',
  'Sacred Kingfisher',
  'Savannah Sparrow',
  'Savi’s Warbler',
  'Scaly-Breasted Munia',
  'Smew',
  'Snowy Egret',
  'Southern Cassowary',
  'Spangled Drongo',
  'Splendid Fairywren',
  'Spotless Crake',
  'Spotted Dove',
  'Squacco Heron',
  'Stubble Quail',
  'Thekla’s Lark',
  'Tree Swallow',
  'Tufted Titmouse',
  'Twite',
  'Vaux’s Swift',
  'Violet Cuckoo',
  'Wedge-Tailed Eagle',
  'Welcome Swallow',
  'Western Tanager',
  'White-Breasted Woodswallow',
  'White-Crowned Sparrow',
  'White-Faced Ibis',
  'White-Headed Duck',
  'White-Throated Swift',
  'Willet',
  'Willie-Wagtail',
  'Willow Tit',
  'Wilson’s Snipe',
  'Wrybill',
  'Yellow-Billed Cuckoo',
  'Zebra Dove',
]
